import gradio as gr
import numpy as np
import cv2
import torch.distributed as dist
import torch
import random
import os

def fix_seed(seed=23333):

    if dist.is_initialized():
        seed = seed + dist.get_rank()

    np.random.seed(seed)
    torch.manual_seed(seed)  
    torch.cuda.manual_seed(seed)  
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

    random.seed(seed)
    np.random.seed(seed)

    os.environ['PYTHONHASHSEED'] = str(seed)


def get_demo(layout_to_image_generation_fn, model_fn):
    colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (0, 255, 255), (255, 0, 255), (128, 0, 0), (0, 128, 0),
              (0, 0, 128), (128, 128, 0), (0, 128, 128), (128, 0, 128), (64, 0, 0), (0, 64, 0), (0, 0, 64)]

    def update_layout_image(custom_layout_dataframe):
        '''
        :param img: RGB
        :param custom_layout_dataframe: dict
        :return:
        '''
        init_layout_image = np.ones((256, 256, 3), dtype=np.uint8) * 255

        bgr_img = cv2.cvtColor(init_layout_image, cv2.COLOR_RGB2BGR)

        print(custom_layout_dataframe)
        for obj_id in range(len(custom_layout_dataframe)):
            obj_class = custom_layout_dataframe['obj_class'][obj_id]
            if obj_class == 'pad':
                continue

            color = colors[obj_id]
            x0, y0, x1, y1 = custom_layout_dataframe['obj_bbox_x0'][obj_id], custom_layout_dataframe['obj_bbox_y0'][obj_id], \
                    custom_layout_dataframe['obj_bbox_x1'][obj_id], custom_layout_dataframe['obj_bbox_y1'][obj_id]

            x0, y0, x1, y1 = int(float(x0) * 256), int(float(y0) * 256), int(float(x1) * 256), int(float(y1) * 256)

            x, y, w, h = x0, y0, x1 - x0, y1 - y0

            cv2.rectangle(bgr_img, (x, y), (x + w, y + h), color, 2)
            text = f"{obj_class}"
            text_w, text_h = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)[0]
            cv2.rectangle(bgr_img, (x + w - text_w, y + h - 2 * text_h), (x + w, y + h), color, -1)
            cv2.putText(bgr_img, text, (x + w - text_w, y + h - text_h), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)

        rgb_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2RGB)

        return rgb_img

    with gr.Blocks() as demo:
        gr.Markdown(
            """
        # LayoutEnc: Leverging Effective Layout Representation for Complex Scene Synthesis
        Get "layout image" and then "layout-to-image generation".
        Thanks to the effective layout representation, we can handle simple-to-complex objects.
        And the results generated by our algorithm show high-fidelty and diversity.
        """
        )
        num_obj = 18
        with gr.Row():
            with gr.Column():
                custom_layout_dataframe = gr.Dataframe(
                    headers=["obj_id", "obj_class", "obj_bbox_x0","obj_bbox_y0","obj_bbox_x1","obj_bbox_y1"],
                    datatype=["number", "str", "number","number","number","number"],
                    row_count=(num_obj + 2, "fixed"),
                    col_count=(6, "fixed"),
                    interactive=False
                )

            with gr.Column():
                with gr.Row():
                    layout_image = gr.Image(label='Layout Image', shape=(256, 256), value=np.ones((256, 256, 3), dtype=np.uint8) * 255).style(width=256, height=256)
                    generated_image = gr.Image(label='Generated Image', shape=(256, 256)).style(width=256, height=256)
                with gr.Row():
                    button_to_update_layout_image = gr.Button(value='Get Layout Image')
                    button_to_update_layout_image.click(fn=update_layout_image, inputs=[custom_layout_dataframe], outputs=[layout_image])
                    generate_button = gr.Button(value='Generate using Layout Image')
                with gr.Row():
                    seed = gr.Number(value=2333, precision=0, label='Seed', interactive=False)

        gr.Examples(
            examples=[
                [
                    [[0, 'image', 0.0, 0.0, 1.0, 1.0],
                     [1, 'tree', 0.0, 0.0, 1.0, 0.2750000059604645],
                     [2, 'grass', 0.0, 0.14166666567325592, 1.0, 1.0, ],
                     [3, 'zebra', 0.18989062309265137, 0.23635415732860565, 0.8281093835830688, 0.8176667094230652],
                     [4, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [5, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [6, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [7, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [8, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [9, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [10, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [11, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [12, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [13, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [14, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [15, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [16, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [17, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [18, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [19, 'pad', 0.0, 0.0, 0.0, 0.0],
                     ],
                    1.0, 25, 3739045
                ],
                [
                    [[0, 'image', 0.0, 0.0, 1.0, 1.0], # done
                     [1, 'door', 0.18039216 , 0.21960784 , 0.30588236 , 0.7254902],
                     [2, 'track',0.003921569 , 0.69411767 , 0.34117648 , 1.0 ],
                     [3, 'train', 0.16078432 , 0.18039216 , 0.9098039 , 0.8392157],
                     [4, 'tree', 0.003921569 , 0.2 , 0.11372549 , 0.56078434],
                     [5, 'background', 0.0 , 0.1254902 , 1.0 , 0.5058824],
                     [6, 'frame', 0.76862746 , 0.1882353 , 0.99215686 , 0.30588236],
                     [7, 'line', 0.6745098 , 0.4745098 , 0.95686275 , 1.0],
                     [8, 'edge', 0.23137255 , 0.49411765 , 0.9098039 , 1.0],
                     [9, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [10, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [11, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [12, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [13, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [14, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [15, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [16, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [17, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [18, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [19, 'pad', 0.0, 0.0, 0.0, 0.0],
                     ],
                    1.0, 25, 7296572
                ],
                [
                    [[0, 'image', 0.0, 0.0, 1.0, 1.0], # done
                     [1, 'building', 0.0 , 0.0 , 0.23137255 , 1.0],
                     [2, 'ear', 0.62352943 , 0.32156864 , 0.827451 , 0.7529412],
                     [3, 'ear', 0.14509805 , 0.29803923 , 0.36078432 , 0.7411765],
                     [4, 'elephant',0.14901961 , 0.17254902 , 0.827451 , 1.],
                     [5, 'top', 0.047058824 , 0.007843138 , 0.14901961 , 0.3098035],
                     [6, 'trunk', 0.44705883 , 0.5137255 , 0.627451 , 1. ],
                     [7, 'roof', 0.7764706 , 0.7176471 , 1.0 , 0.89803 ],
                     [8, 'building', 0.7647059 , 0.72156864 , 1.0 , 1.0],
                     [9, 'tree', 0.64705884 , 0.29411766 , 0.9490196 , 0.9882356],
                     [10, 'sky', 0.0 , 0.0 , 1.0 , 0.74117659805],
                     [11, 'cloud', 0.22745098 , 0.0 , 0.84705883 , 0.1647058],
                     [12, 'roof', 0.0 , 0.22352941 , 0.23137255 , 0.56862],
                     [13, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [14, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [15, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [16, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [17, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [18, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [19, 'pad', 0.0, 0.0, 0.0, 0.0],
                     ],
                    1.0, 25, 290
                ],
                [
                    [[0, 'image', 0.0, 0.0, 1.0, 1.0], # done
                     [1, 'man', 0.16078432 , 0.14901961 , 0.4117647 , 0.584313],
                     [2, 'pole', 0.23137255 , 0.20392157 , 0.40392157 , 0.3960784],
                     [3, 'jacket', 0.003921569 , 0.003921569 , 0.99607843 , 1.0 ],
                     [4, 'mountain', 0.5137255 , 0.19607843 , 0.9411765 , 0.6],
                     [5, 'snow', 0.003921569 , 0.6431373 , 1.0 , 0.960784],
                     [6, 'ground', 0.00784314, 1.0 , 0.64705884, 0.9647059],
                     [7, 'pant', 0.18431373 , 0.3764706 , 0.34509805 , 0.55686],
                     [8, 'part', 0.6313726 , 0.17254902 , 1.0 , 0.5019608],
                     [9, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [10, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [11, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [12, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [13, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [14, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [15, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [16, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [17, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [18, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [19, 'pad', 0.0, 0.0, 0.0, 0.0],
                    ],
                    1.0, 25, 290
                ],
                [
                    [[0, 'image', 0.0, 0.0, 1.0, 1.0], #done
                     [1, 'rock', 0.0 , 0.6745098 , 0.34901962 , 0.8745090],
                     [2, 'sky', 0.0 , 0.003921569 , 0.654902 , 0.494117652],
                     [3, 'track', 0.0 , 0.6627451 , 0.7411765 , 0.9960784],
                     [4, 'train', 0.0 , 0.0 , 1.0 , 0.996],
                     [5, 'wheel', 0.6784314 , 0.7921569 , 0.79607844 , 0.992153],
                     [6, 'window', 0.5882353 , 0.07450981 , 0.7176471 , 0.2784315],
                     [7, 'stripe', 0.11764706 , 0.30980393 , 0.85882354 , 0.55686],
                     [8, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [9, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [10, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [11, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [12, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [13, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [14, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [15, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [16, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [17, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [18, 'pad', 0.0, 0.0, 0.0, 0.0],
                     [19, 'pad', 0.0, 0.0, 0.0, 0.0],
                    ],
                    1.0, 25, 290
                ],
            ],
            inputs=[
                custom_layout_dataframe
            ],
            label='Update Layout Using Examples'
        )

        def custom_layout_dataframe_to_dict(custom_layout_dataframe):
            obj_bbox = []
            for x0,y0,x1,y1 in zip(custom_layout_dataframe['obj_bbox_x0'],custom_layout_dataframe['obj_bbox_y0']
                    ,custom_layout_dataframe['obj_bbox_x1'], custom_layout_dataframe['obj_bbox_y1']):
                obj_bbox.append([float(x0),float(y0),float(x1),float(y1)])
            custom_layout_dict = {
                'num_obj': len(custom_layout_dataframe),
                'obj_class': custom_layout_dataframe['obj_class'],
                'obj_bbox': obj_bbox
            }
            return custom_layout_dict

        def layout_to_image_generation(custom_layout_dataframe):

            custom_layout_dict = custom_layout_dataframe_to_dict(custom_layout_dataframe)

            return layout_to_image_generation_fn(model_fn, custom_layout_dict)

        generate_button.click(
            fn=layout_to_image_generation, inputs=[custom_layout_dataframe], outputs=[generated_image]
        )

    return demo
