model:
  base_learning_rate: 4.5e-06
  target: layoutenc.models.cond_transformer_w_layoutenc.Net2NetTransformer
  params:
    vqvae_ckpt_path: data/pretrained/checkpoints/vg/vqvae_vg.ckpt
    transformer_config:
      target: layoutenc.models.mingpt.GPT
      params:
        vocab_size: 8192
        block_size: 406 # 30+60+60+1+255
        n_layer: 24
        n_head: 16
        n_embd: 1024
        resid_pdrop: 0.1
        attn_pdrop: 0.1
        embd_pdrop: 0.1
        class_num: 179
        num_obj: 30
    first_stage_config:
      target: layoutenc.modules.taming.models.vqgan.VQModel
      params:
        embed_dim: 256
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: layoutenc.modules.taming.modules.losses.DummyLoss
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4 #28
    num_workers: 8
    train:
      target: layoutenc.data.dataloader_vg.VgDataset
      params:
        size: 296
        crop_size: 256
        vocab: data/vg_other_annotations/vocab.json
        image_dir: data/vg/images/
        h5_path: data/vg_other_annotations/train.h5
        max_objects: 30
        left_right_flip: true
        crop_type: random
        mask_inst_only: true
    validation:
      target: layoutenc.data.dataloader_vg.VgDataset
      params:
        size: 256
        crop_size: 256
        vocab: data/vg_other_annotations/vocab.json
        image_dir: data/vg/images/
        h5_path: data/vg_other_annotations/test.h5
        max_objects: 30
        left_right_flip: false
        crop_type: none
        mask_inst_only: true
